"""add account_type to Wallet model

Revision ID: 305f6661b42b
Revises: 38bd33837d29
Create Date: 2026-08-06 10:53:05.616356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '305f6661b42b'
down_revision: Union[str, Sequence[str], None] = '38bd33837d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('client_secret', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('destination_wallet_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_payment_error', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_client_secret'), 'payment_intents', ['client_secret'], unique=True)
    op.create_index(op.f('ix_payment_intents_destination_wallet_id'), 'payment_intents', ['destination_wallet_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_idempotency_key'), 'payment_intents', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_intents_purpose'), 'payment_intents', ['purpose'], unique=False)
    op.create_index(op.f('ix_payment_intents_reference_id'), 'payment_intents', ['reference_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_status'), 'payment_intents', ['status'], unique=False)
    op.create_index(op.f('ix_payment_intents_user_id'), 'payment_intents', ['user_id'], unique=False)
    op.add_column('wallets', sa.Column('account_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_wallets_account_type'), 'wallets', ['account_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_account_type'), table_name='wallets')
    op.drop_column('wallets', 'account_type')
    op.drop_index(op.f('ix_payment_intents_user_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_status'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_reference_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_purpose'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_idempotency_key'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_destination_wallet_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_client_secret'), table_name='payment_intents')
    op.drop_table('payment_intents')
    # ### end Alembic commands ###
