"""phase2_ledger_improvements

Revision ID: 38bd33837d29
Revises: 62241b6cf45f
Create Date: 2026-08-02 19:00:49.134772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38bd33837d29'
down_revision: Union[str, Sequence[str], None] = '62241b6cf45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'reference_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'reference_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
